### ISSUE TITLE
PHP Warning: Use of undefined constant ENCODE_AMPERSANDS - assumed 'ENCODE_AMPERSANDS'

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/cron_info#11]
```
PHP Warning: Use of undefined constant ENCODE_AMPERSANDS - assumed 'ENCODE_AMPERSANDS' (this will throw an Error in a future version of PHP) in /home/bibo/contao4go/contao35/system/modules/cron_info/modules/CronRegistry.php on line 42
#0 system/modules/cron_info/modules/CronRegistry.php(42): __error_enhanced(2, 'Use of undefined constant ENCODE_AMPERSANDS - assumed 'ENCODE_AMPERSANDS' (this will throw an Error in a future version of PHP)', 'system/modules/cron_info/modules/CronRegistry.php', 42, Array)
#1 system/modules/core/classes/BackendModule.php(98): BugBuster\CronInfo\CronRegistry->compile()
#2 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#3 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('cron_info')
#4 contao/main.php(20): Contao\BackendMain->run()
```

**Comment by BugBuster1701** [comment]
Durch true ersetzen
