### ISSUE TITLE
 Fatal error: Uncaught exception 'Exception' with message 'The PHP mcrypt extension is not installed'

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/cron_info#12]
```
PHP Fatal error: Uncaught exception 'Exception' with message 'The PHP mcrypt extension is not installed' thrown in /home/bibo/contao4go/contao35/system/modules/core/library/Contao/Encryption.php on line 157
#0 system/modules/core/library/Contao/Encryption.php(76): Contao\Encryption::initialize()
#1 system/modules/cron_info/modules/CronRegistry.php(330): Contao\Encryption::encrypt('a:2:{i:0;s:9:"Automator";i:1;s:15:"purgeImageCache";}')
#2 system/modules/cron_info/modules/CronRegistry.php(104): BugBuster\CronInfo\CronRegistry->getCronRegistrations()
#3 system/modules/core/classes/BackendModule.php(98): BugBuster\CronInfo\CronRegistry->compile()
#4 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#5 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('cron_info')
#6 contao/main.php(20): Contao\BackendMain->run()
```
PHP 7.2 ohne mcrypt!

**Comment by BugBuster1701** [comment]
Aus contao-cron die Klasse Cron_Encryption benutzen.
